# syntax=docker/dockerfile:1

FROM golang:1.19 as build

WORKDIR /go/src/app
COPY . .

RUN go mod download

RUN CGO_ENABLED=0 go build -o /go/bin/snippetbox ./cmd/web

FROM gcr.io/distroless/static-debian11

COPY --from=build /go/bin/snippetbox /

CMD ["/snippetbox"]
